### PR TITLE
Add a wildcard reload command

### PR DESCRIPTION
**Pull request by SpicyTakis**

### CODE REVIEW

**Review by aikocc — CHANGES_REQUESTED** [review]
This could all be replaced by self.bot.load_all_extensions()

**Comment by SpicyTakis** [comment]
are you fucking kidding me
...

**Comment by aikocc** [comment]
no, you can see the code [here](https://github.com/Voxel-Fox-Ltd/VoxelBotUtils/blob/8051c66fe960204e3ab263bb499506eb31ed3ee9/voxelbotutils/cogs/utils/custom_bot.py#L402-L426)

**Comment by 4Kaylum** [comment]
We talked about this on the server and you actually already used it: https://discord.com/channels/208895639164026880/636085718002958336/772966244084482048

**Pull request merged**
